# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todolist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todolist.proto',
  package='todo.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x0etodolist.proto\x12\rtodo.protobuf\"\x0e\n\x0c\x45mptyRequest\"I\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cis_completed\x18\x03 \x01(\x08\x12\x11\n\tis_active\x18\x04 \x01(\x08\".\n\x08TodoList\x12\"\n\x05todos\x18\x01 \x03(\x0b\x32\x13.todo.protobuf.Todo\"\xc9\x01\n\x15OperationTodoResponse\x12!\n\x04todo\x18\x01 \x01(\x0b\x32\x13.todo.protobuf.Todo\x12\x41\n\top_status\x18\x02 \x01(\x0e\x32..todo.protobuf.OperationTodoResponse.OP_Status\"J\n\tOP_Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x12\x0b\n\x07UPDATED\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x32\xe2\x02\n\x0bTodoService\x12\x43\n\x0bGetAllTodos\x12\x1b.todo.protobuf.EmptyRequest\x1a\x17.todo.protobuf.TodoList\x12\x33\n\x07GetTodo\x12\x13.todo.protobuf.Todo\x1a\x13.todo.protobuf.Todo\x12G\n\nCreateTodo\x12\x13.todo.protobuf.Todo\x1a$.todo.protobuf.OperationTodoResponse\x12G\n\nDeleteTodo\x12\x13.todo.protobuf.Todo\x1a$.todo.protobuf.OperationTodoResponse\x12G\n\nUpdateTodo\x12\x13.todo.protobuf.Todo\x1a$.todo.protobuf.OperationTodoResponseb\x06proto3')
)



_OPERATIONTODORESPONSE_OP_STATUS = _descriptor.EnumDescriptor(
  name='OP_Status',
  full_name='todo.protobuf.OperationTodoResponse.OP_Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=300,
  serialized_end=374,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONTODORESPONSE_OP_STATUS)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='todo.protobuf.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=47,
)


_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='todo.protobuf.Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo.protobuf.Todo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='todo.protobuf.Todo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_completed', full_name='todo.protobuf.Todo.is_completed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='todo.protobuf.Todo.is_active', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=122,
)


_TODOLIST = _descriptor.Descriptor(
  name='TodoList',
  full_name='todo.protobuf.TodoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todos', full_name='todo.protobuf.TodoList.todos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=170,
)


_OPERATIONTODORESPONSE = _descriptor.Descriptor(
  name='OperationTodoResponse',
  full_name='todo.protobuf.OperationTodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='todo.protobuf.OperationTodoResponse.todo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_status', full_name='todo.protobuf.OperationTodoResponse.op_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPERATIONTODORESPONSE_OP_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=374,
)

_TODOLIST.fields_by_name['todos'].message_type = _TODO
_OPERATIONTODORESPONSE.fields_by_name['todo'].message_type = _TODO
_OPERATIONTODORESPONSE.fields_by_name['op_status'].enum_type = _OPERATIONTODORESPONSE_OP_STATUS
_OPERATIONTODORESPONSE_OP_STATUS.containing_type = _OPERATIONTODORESPONSE
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['Todo'] = _TODO
DESCRIPTOR.message_types_by_name['TodoList'] = _TODOLIST
DESCRIPTOR.message_types_by_name['OperationTodoResponse'] = _OPERATIONTODORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:todo.protobuf.EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), dict(
  DESCRIPTOR = _TODO,
  __module__ = 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:todo.protobuf.Todo)
  ))
_sym_db.RegisterMessage(Todo)

TodoList = _reflection.GeneratedProtocolMessageType('TodoList', (_message.Message,), dict(
  DESCRIPTOR = _TODOLIST,
  __module__ = 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:todo.protobuf.TodoList)
  ))
_sym_db.RegisterMessage(TodoList)

OperationTodoResponse = _reflection.GeneratedProtocolMessageType('OperationTodoResponse', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONTODORESPONSE,
  __module__ = 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:todo.protobuf.OperationTodoResponse)
  ))
_sym_db.RegisterMessage(OperationTodoResponse)



_TODOSERVICE = _descriptor.ServiceDescriptor(
  name='TodoService',
  full_name='todo.protobuf.TodoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=377,
  serialized_end=731,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllTodos',
    full_name='todo.protobuf.TodoService.GetAllTodos',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_TODOLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodo',
    full_name='todo.protobuf.TodoService.GetTodo',
    index=1,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTodo',
    full_name='todo.protobuf.TodoService.CreateTodo',
    index=2,
    containing_service=None,
    input_type=_TODO,
    output_type=_OPERATIONTODORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTodo',
    full_name='todo.protobuf.TodoService.DeleteTodo',
    index=3,
    containing_service=None,
    input_type=_TODO,
    output_type=_OPERATIONTODORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTodo',
    full_name='todo.protobuf.TodoService.UpdateTodo',
    index=4,
    containing_service=None,
    input_type=_TODO,
    output_type=_OPERATIONTODORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOSERVICE)

DESCRIPTOR.services_by_name['TodoService'] = _TODOSERVICE

# @@protoc_insertion_point(module_scope)
