"""change is_active column

Revision ID: 0c7e4ccb950d
Revises: 0c9148aef8c4
Create Date: 2018-08-20 15:12:55.094346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7e4ccb950d'
down_revision = '0c9148aef8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
